import 'package:flutter_dino/models/enemy_data.dart';
import 'package:flutter_dino/resources/enemies.dart';

class EnemySelector {
  static Map<String, EnemyData> _enemyMap = {
    Enemies.bat: EnemyData(
      name: Enemies.bat,
      width: 46,
      height: 30,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 12,
      columnsRun: 7,
      speed: 200,
      canFly: true,
    ),
    Enemies.bee: EnemyData(
      name: Enemies.bee,
      width: 36,
      height: 34,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 6,
      columnsRun: 6,
      speed: 300,
      canFly: true,
    ),
    Enemies.bird: EnemyData(
      name: Enemies.bird,
      width: 32,
      height: 32,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 9,
      columnsRun: 9,
      speed: 250,
      canFly: true,
    ),
    Enemies.bunny: EnemyData(
      name: Enemies.bunny,
      width: 34,
      height: 44,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 8,
      columnsRun: 12,
      speed: 250,
      canFly: false,
    ),
    Enemies.chicken: EnemyData(
      name: Enemies.chicken,
      width: 32,
      height: 34,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 13,
      columnsRun: 14,
      speed: 200,
      canFly: false,
    ),
    Enemies.duck: EnemyData(
      name: Enemies.duck,
      width: 36,
      height: 36,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 10,
      columnsRun: 10,
      speed: 200,
      canFly: false,
    ),
    Enemies.fat: EnemyData(
      name: Enemies.fat,
      width: 40,
      height: 48,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 8,
      columnsRun: 8,
      speed: 175,
      canFly: false,
    ),
    Enemies.ghost: EnemyData(
      name: Enemies.ghost,
      width: 44,
      height: 30,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 10,
      columnsRun: 10,
      speed: 200,
      canFly: false,
    ),
    Enemies.mushroom: EnemyData(
      name: Enemies.mushroom,
      width: 32,
      height: 32,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 14,
      columnsRun: 16,
      speed: 175,
      canFly: false,
    ),
    Enemies.pig: EnemyData(
      name: Enemies.pig,
      width: 36,
      height: 30,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 9,
      columnsRun: 12,
      speed: 200,
      canFly: false,
    ),
    Enemies.radish: EnemyData(
      name: Enemies.radish,
      width: 30,
      height: 38,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 6,
      columnsRun: 12,
      speed: 175,
      canFly: false,
    ),
    Enemies.rhino: EnemyData(
      name: Enemies.rhino,
      width: 52,
      height: 34,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 11,
      columnsRun: 6,
      speed: 250,
      canFly: false,
    ),
    Enemies.rock: EnemyData(
      name: Enemies.rock,
      width: 22,
      height: 18,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 11,
      columnsRun: 14,
      speed: 175,
      canFly: false,
    ),
    Enemies.slime: EnemyData(
      name: Enemies.slime,
      width: 44,
      height: 30,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 10,
      columnsRun: 10,
      speed: 175,
      canFly: false,
    ),
    Enemies.trunk: EnemyData(
      name: Enemies.trunk,
      width: 64,
      height: 32,
      rowsIdle: 1,
      rowsRun: 1,
      columnsIdle: 18,
      columnsRun: 14,
      speed: 175,
      canFly: false,
    ),
  };

  static EnemyData enemy({required String enemyType}) => _enemyMap[enemyType]!;
}
